type HealthData {
  height: Float
  user: User @relation
  weight: Float
}

type User {
  email: String! @unique
  healthData: HealthData
  issuer: String! @unique
  name: String
}

type Query {
  userByEmail(email: String!): User
}
