type HealthData {
  user: User @relation
  weight: Float
  height: Float
}

type User {
  name: String
  email: String! @unique
  healthData: HealthData
}

type Query {
  userByEmail(email: String!): User
}
